VOXEL_SIZE = 0.2
MAX_RANGE = 60
GROUND_THRESHOLD = -1.4
CLUSTER_EPS = 0.6
CLUSTER_MIN_POINTS = 15
CLUSTER_Z_SCALE = 0.25
USE_ADAPTIVE_CLUSTER = True

# Range-adaptive clustering (near -> far)
ADAPTIVE_CLUSTER_RANGE_BINS = (0.0, 20.0, 35.0, 60.0)
ADAPTIVE_CLUSTER_EPS_SCALES = (0.75, 1.0, 1.25)
ADAPTIVE_CLUSTER_MIN_SCALES = (1.4, 1.0, 0.75)

# ROI/FOV filtering tuned for KITTI front camera overlap.
ROI_X_MIN = 0.0
ROI_X_MAX = 70.0
ROI_Y_ABS_MAX = 35.0
ROI_Z_MIN = -2.5
ROI_Z_MAX = 1.5
CAMERA_FOV_X_OVER_Z_MAX = 1.0
CAMERA_MIN_DEPTH = 1.0

# Physical 3D box sanity filters.
MIN_BOX_HWL = (0.8, 0.25, 0.25)
MAX_BOX_HWL = (3.2, 3.2, 12.0)

BEV_RESOLUTION = 0.05
ENABLE_INTENSITY_COMP = True
RANGE_ATTENUATION_ALPHA = 0.0
USE_EWMA_FUSION = True
EWMA_ALPHA = 0.6
FUSION_WINDOW = 10
ENABLE_VISUALIZATION = True
VISUALIZE_EVERY_N = 0
